# Generated by Django 2.2.5 on 2019-09-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KeywordExample',
            new_name='Example',
        ),
    ]
