# Generated by Django 2.2.5 on 2019-09-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_auto_20190926_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Video'), (2, 'Text')], null=True),
        ),
    ]
