# Generated by Django 2.2.5 on 2019-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0005_auto_20190926_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='active',
            field=models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1),
        ),
    ]
