# Generated by Django 2.2.5 on 2019-09-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0006_keyword_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='active',
            field=models.IntegerField(choices=[(1, 'Active'), (0, 'Inactive')], default=1),
        ),
    ]
