# Generated by Django 2.2.5 on 2019-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0011_auto_20190928_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='channel_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='illegal_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='website',
            name='result_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
