# Generated by Django 2.2.5 on 2019-09-28 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0012_auto_20190928_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='active',
            new_name='status',
        ),
    ]
