# Generated by Django 2.2.5 on 2019-09-28 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_channel', to='channels.Channel', verbose_name='Channel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='keyword',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_keyword', to='keywords.Keyword', verbose_name='Keyword'),
            preserve_default=False,
        ),
    ]
