# Generated by Django 2.2.5 on 2019-09-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20190928_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='content_status',
            field=models.IntegerField(choices=[(0, 'Legal'), (1, 'Illegal')], default=0),
        ),
    ]
