# Generated by Django 2.2.5 on 2019-09-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_report_content_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content_status',
        ),
        migrations.AddField(
            model_name='report',
            name='type',
            field=models.IntegerField(choices=[(0, 'LEGAL'), (1, 'ILLEGAL')], default=0),
        ),
    ]
