# Generated by Django 2.2.5 on 2019-09-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0013_auto_20190928_0955'),
        ('reports', '0005_auto_20190928_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='example',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_example', to='keywords.Example', verbose_name='Example'),
            preserve_default=False,
        ),
    ]
