# Generated by Django 2.2.5 on 2019-09-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
