# Generated by Django 2.2.5 on 2019-09-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20190928_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='date_finished',
            new_name='finished_at',
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
