# Generated by Django 2.2.5 on 2019-09-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20190928_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'LEGAL'), (2, 'ILLEGAL')], null=True),
        ),
    ]
