# Generated by Django 2.2.5 on 2019-09-26 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='page',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
