# Generated by Django 2.2.5 on 2019-09-26 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20190926_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='page',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
